Tests hotifx
kbss-cvut/jopa pull request #164
Opened 2023-05-22 11:20 UTC by syrcheddar

2023-05-22 11:32 UTC, ledsoft requested changes
See the inline comments.

2023-05-22 11:32 UTC, ledsoft commented on modelgen/src/test/java/cz/cvut/kbss/jopa/modelgen/OutputFilesGeneratorTests.java
> +    static final String expectedResult = readFileAsString(new File("./src/test/resources/TestingClassOWL_.txt"));
Remove unused constant.

2023-05-22 11:32 UTC, ledsoft commented on modelgen/src/test/java/cz/cvut/kbss/jopa/modelgen/OutputFilesGeneratorTests.java
> +            assertTrue(actualResult.contains("public static volatile ListAttribute<TestingClassOWL, Test> data-list;"));
This is not a valid Java field name - you cannot use `-` in names.

2023-05-22 11:32 UTC, ledsoft commented on modelgen/src/test/java/cz/cvut/kbss/jopa/modelgen/OutputFilesGeneratorTests.java
> -                System.err.println("Chyba cteni");
This catch is useless (in the static method on line 159). Throw a runtime exception wrapping the IO exception or declare the whole method to throw the IOException.

2023-05-22 12:53 UTC, syrcheddar commented on modelgen/src/main/java/cz/cvut/kbss/jopa/modelgen/ModelGenProcessor.java
> -                if (paramAnnotation.toString().contains("cz.cvut.kbss.jopa.model.annotations.Transient")) {
i'm not sure if this check is nessecary or not

2023-05-23 08:19 UTC, ledsoft approved these changes
LGTM

2023-05-23 08:19 UTC, merged