Semantic Criteria API
kbss-cvut/jopa pull request #91
Opened 2021-05-18 14:52 UTC by marcel-zec

Implementation of Semantic Criteria API.

2021-06-01 10:52 UTC, ledsoft requested changes
See the inline comments.

2021-06-01 10:52 UTC, ledsoft commented on jopa-impl/src/main/java/cz/cvut/kbss/jopa/query/criteria/PathImpl.java
> +//    }
Please, remove this commented-out code

2021-06-01 10:52 UTC, ledsoft commented on jopa-impl/src/main/java/cz/cvut/kbss/jopa/query/criteria/CriteriaParameterFiller.java
> +            else query.setParameter(name, literalParameters.get(name).getValue());
Please, try to use a more consistent parentheses policy. Sometimes you have if(-else) with parentheses, sometimes without.  Generally, I prefer parentheses to be present.

2021-06-01 10:52 UTC, ledsoft commented on jopa-impl/src/main/java/cz/cvut/kbss/jopa/query/criteria/expressions/ExpressionNotLikeImpl.java
> +public class ExpressionNotLikeImpl extends AbstractComparisonExpression {
Can't this just be a negated `ExpressionLikeImpl`?

2021-06-01 10:52 UTC, ledsoft commented on jopa-impl/src/test/java/cz/cvut/kbss/jopa/query/criteria/CriteriaBuilderTest.java
> +//        criteriaParameterFiller = new CriteriaParameterFiller();
Please, remove this commented-out code.

2021-06-16 09:17 UTC, marcel-zec commented
> See the inline comments.

The requested changes have been made in 194842b commit.

2021-06-24 10:15 UTC, ledsoft approved these changes

2021-06-24 10:15 UTC, merged